import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ClerkProvider, ClerkLoading, ClerkLoaded } from "@clerk/nextjs"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Clerk Authentication Demo',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <ClerkLoading>
            <div className='flex justify-center items-center w-full h-screen'>
              Loading...
            </div>
          </ClerkLoading>
          <ClerkLoaded>
            {children}
          </ClerkLoaded>
        </body>
      </html>
    </ClerkProvider>
  )
}
